# 网站设置
title: My Blog
SEOTitle: My Blog | A Collection of Thoughts
header-img: img/post-bg-default.jpg
email: chenglong799466@gmail.com
description: "Welcome to my blog! Here I share my thoughts and ideas."
keyword: "blog, thoughts, ideas"
url: "https://www.myblog.com"
baseurl: ""
github_repo: "https://github.com/chenglong799466/chenglong799466.github.io"

# 侧边栏设置
sidebar: true
sidebar-about-description: "I'm a passionate writer and love to share my insights."
sidebar-avatar: /img/avatar.jpg

# 社交网络设置
RSS: true
weibo_username: username
zhihu_username: username
github_username: username
twitter_username: username

# 构建设置
permalink: pretty
paginate: 10
exclude: [ "less", "node_modules", "Gruntfile.js", "package.json", "README.md" ]
anchorjs: true

# Gems
gems: [ jekyll-paginate ]

# Markdown 设置
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# 评论系统
disqus_username: mydisqusname

# 统计
ba_track_id: b50bf2b12b5338a1845e33832976fd68
ga_track_id: 'UA-90855596-1'
ga_domain: auto

# 特色标签
featured-tags: true
featured-condition-size: 3

# 渐进式 Web 应用
chrome-tab-theme-color: "#000000"
service-worker: true

# 友情链接
friends:
  - title: Friend 1
    href: https://friend1.com
  - title: Friend 2
    href: https://friend2.com
  - title: Friend 3
    href: https://friend3.com